all: shell cmd1 cmd2 cmd3
shell: shell.c
	gcc -o shell shell.c
cmd1: cmd1.c
	gcc -o cmd1 cmd1.c
cmd2: cmd2.c
	gcc -o cmd2 cmd2.c
cmd3: cmd3.c
	gcc -o cmd3 cmd3.c
clean:  
	rm -rf cmd1 cmd2 cmd3 shell
